# -*- coding: utf-8 -*-
"""TA1_Vergara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3DEed6aob-wl5J2hhYiy7A5GGgi5OP7
"""

!pip install agentpy

import agentpy as ap
import random
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# -------- Get user input from console --------
num_agents = int(input("Enter number of agents: "))
grid_size = int(input("Enter grid size (e.g., 10 for 10x10): "))
num_steps = int(input("Enter number of steps: "))

# -------- Agent Definition -----------
class RandomWalker(ap.Agent):
    def step(self):
        direction = random.choice([(1,0), (-1,0), (0,1), (0,-1)])
        x, y = self.position
        # Keep agents inside grid
        x = max(0, min(self.model.p.grid_size[0]-1, x + direction[0]))
        y = max(0, min(self.model.p.grid_size[1]-1, y + direction[1]))
        self.position = (x, y)

# -------- Model Definition -----------
class RandomWalkModel(ap.Model):
    def setup(self):
        # Create agents
        self.agents = ap.AgentList(self, self.p.agents, RandomWalker)

        # Initialize random positions
        for agent in self.agents:
            agent.position = (random.randint(0, self.p.grid_size[0]-1),
                              random.randint(0, self.p.grid_size[1]-1))

        # Create grid (optional)
        self.grid = ap.Grid(self, self.p.grid_size, torus=False)
        self.grid.add_agents(self.agents)

    def step(self):
        for agent in self.agents:
            agent.step()

# -------- Parameters from user input -----------
parameters = {
    'agents': num_agents,
    'grid_size': (grid_size, grid_size),
    'steps': num_steps
}

# -------- Run Model -----------
model = RandomWalkModel(parameters)
model.setup()

# -------- Interactive Animation -----------
fig, ax = plt.subplots()
ax.set_xlim(0, model.p.grid_size[0])
ax.set_ylim(0, model.p.grid_size[1])
ax.set_xticks(range(model.p.grid_size[0]+1))
ax.set_yticks(range(model.p.grid_size[1]+1))
ax.grid(True)

scat = ax.scatter([], [], s=200)  # s = size of agents

def update(frame):
    model.step()
    x = [agent.position[0] for agent in model.agents]
    y = [agent.position[1] for agent in model.agents]
    scat.set_offsets(list(zip(x, y)))
    return scat,

ani = animation.FuncAnimation(fig, update, frames=model.p.steps, blit=True, repeat=False)
plt.show()

import random
import agentpy as ap
import matplotlib.pyplot as plt

# 1. AGENT CLASS DEFINITION
class SmartWalker(ap.Agent):
    """
    Agent with trajectory tracking and modified directional movement rules.
    """
    def setup(self):
        # Initialize agent at a random coordinate within grid bounds
        self.position = (
            random.randint(0, self.model.p.grid_size[0] - 1),
            random.randint(0, self.model.p.grid_size[1] - 1)
        )
        # Laboratory Task 1: Record and track the complete path
        self.path = [self.position]

    def step(self):
        # Laboratory Task 2: Movement rules modification
        # Biased movement preference: Higher likelihood to step right or up
        directions = [(1, 0), (-1, 0), (0, 1), (0, -1)]
        weights = [0.4, 0.2, 0.3, 0.1]  # 40% Right, 20% Left, 30% Up, 10% Down

        move = random.choices(directions, weights=weights, k=1)[0]

        # Bounded Movement: Keep coordinates strictly inside the grid limits
        new_x = max(0, min(self.model.p.grid_size[0] - 1, self.position[0] + move[0]))
        new_y = max(0, min(self.model.p.grid_size[1] - 1, self.position[1] + move[1]))

        self.position = (new_x, new_y)
        self.path.append(self.position)

# 2. MODEL CLASS DEFINITION
class RandomWalkModel(ap.Model):
    """
    Model environment to manage agent population and grid boundaries.
    """
    def setup(self):
        self.agents = ap.AgentList(self, self.p.agents, SmartWalker)
        self.grid = ap.Grid(self, self.p.grid_size, torus=False)
        self.grid.add_agents(self.agents)

    def step(self):
        self.agents.step()

# 3. USER INPUTS & SIMULATION EXECUTION
# Get inputs dynamically via Colab console prompts
num_agents = int(input("Enter number of agents: "))
grid_size = int(input("Enter grid size: "))
num_steps = int(input("Enter number of steps: "))

parameters = {
    'agents': num_agents,
    'grid_size': (grid_size, grid_size),
    'steps': num_steps
}

model = RandomWalkModel(parameters)
model.run()

# 4. VISUALIZATION: TRAJECTORY PATHS & FINAL POSITIONS
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 6))

# Subplot 1: Agent Trajectory Paths (Task 1)
ax1.set_xlim(-0.5, parameters['grid_size'][0] - 0.5)
ax1.set_ylim(-0.5, parameters['grid_size'][1] - 0.5)
ax1.set_xticks(range(parameters['grid_size'][0]))
ax1.set_yticks(range(parameters['grid_size'][1]))
ax1.grid(True, linestyle="--", alpha=0.5)
ax1.set_title("Task 1: Agent Paths & Trajectories", fontsize=11, fontweight='bold')

colors = plt.cm.tab10.colors
for i, agent in enumerate(model.agents):
    px, py = zip(*agent.path)
    c = colors[i % len(colors)]
    # Path line
    ax1.plot(px, py, linestyle='-', marker='o', markersize=3, alpha=0.7, color=c, label=f"Agent {agent.id}")
    # Starting location (square) and Ending location (triangle)
    ax1.plot(px[0], py[0], marker='s', markersize=7, color=c)
    ax1.plot(px[-1], py[-1], marker='^', markersize=8, color=c)

ax1.legend(bbox_to_anchor=(1.03, 1), loc='upper left', fontsize='small')

# Subplot 2: Final Distribution Analysis (Task 3)
ax2.set_xlim(-0.5, parameters['grid_size'][0] - 0.5)
ax2.set_ylim(-0.5, parameters['grid_size'][1] - 0.5)
ax2.set_xticks(range(parameters['grid_size'][0]))
ax2.set_yticks(range(parameters['grid_size'][1]))
ax2.grid(True, linestyle="--", alpha=0.5)
ax2.set_title("Task 3: Final Agent Positions Distribution", fontsize=11, fontweight='bold')

final_x = [agent.path[-1][0] for agent in model.agents]
final_y = [agent.path[-1][1] for agent in model.agents]
ax2.scatter(final_x, final_y, s=120, color='crimson', edgecolors='black', zorder=3)

for agent in model.agents:
    fx, fy = agent.path[-1]
    ax2.annotate(f"A{agent.id}", (fx + 0.15, fy + 0.15), fontsize=9, fontweight='bold')

plt.suptitle("CS0065 Technical Assessment 1 — Justin D. Vergara (AN41)", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# 5. CONSOLE OUTPUT: FINAL POSITION & DISPLACEMENT LOGS
print("\n" + "="*60)
print("CS0065 TA1: FINAL POSITIONS & DISPLACEMENT ANALYSIS")
print("Programmed by: Justin D. Vergara - AN41")
print("="*60)
for agent in model.agents:
    start_pos = agent.path[0]
    end_pos = agent.path[-1]
    dx = end_pos[0] - start_pos[0]
    dy = end_pos[1] - start_pos[1]
    print(f"Agent {agent.id:02d} | Start: {start_pos} -> End: {end_pos} | Net Displacement: ({dx:+d}, {dy:+d})")
print("="*60)